---
title: "Visualization"
author: "Shrinath"
date: "May 29, 2018"
output: html_document
---

```{r}
library(ggplot2)
library(data.table)
df <- fread('Economist_Assignment_Data.csv',drop=1)
```



```{r}
head(df)

```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point()
```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)

```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region))+geom_point(size=4,shape=1)+geom_smooth(aes(group=1))

```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')

```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))

```



```{r}
pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                   "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                   "India", "Italy", "China", "South Africa", "Spane",
                   "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                   "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                   "New Zealand", "Singapore")

ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))+ geom_text(aes(label = Country), color = "gray20", data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)+theme_bw()

```




```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))+ geom_text(aes(label = Country), color = "gray20",data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)+theme_bw()+scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",limits = c(.9, 10.5),breaks=1:10) 
```


```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))+ geom_text(aes(label = Country), color = "gray20",data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)+theme_bw()+scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",limits = c(.9, 10.5),breaks=1:10) + scale_y_continuous(name = "Human Development Index, 2011 (1=Best)",limits = c(0.2, 1.0))

```



```{r}
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula = y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))+ geom_text(aes(label = Country), color = "gray20",data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)+theme_bw()+scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",limits = c(.9, 10.5),breaks=1:10) + scale_y_continuous(name = "Human Development Index, 2011 (1=Best)",limits = c(0.2, 1.0))+ggtitle("Corruption and Human development")

```



```{r}
library(ggthemes)
ggplot(df,aes(x=CPI,y=HDI,color=Region)) + geom_point(size=4,shape=1)+geom_smooth(aes(group=1))+ geom_smooth(aes(group=1),method ='lm',formula=y~log(x),se=FALSE,color='red')+geom_text(aes(label=Country))+ geom_text(aes(label = Country), color = "gray20",data = subset(df, Country %in% pointsToLabel),check_overlap = TRUE)+theme_bw()+scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",limits = c(.9, 10.5),breaks=1:10) + scale_y_continuous(name = "Human Development Index, 2011 (1=Best)",limits = c(0.2, 1.0))+ggtitle("Corruption and Human development")+ theme_economist_white()

```